version: '3.8'

services:
  # Lightweight PostgreSQL for development
  postgres:
    image: postgis/postgis:15-3.3
    container_name: ai-travel-postgres-dev
    environment:
      POSTGRES_DB: ai_travel_db
      POSTGRES_USER: travel_user
      POSTGRES_PASSWORD: travel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./backend/sql/postgis-init.sql:/docker-entrypoint-initdb.d/02-postgis.sql
    # Optimized for development - lower memory usage
    command: >
      postgres 
      -c shared_buffers=128MB
      -c effective_cache_size=256MB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travel_user -d ai_travel_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis with memory limit
  redis:
    image: redis:7-alpine
    container_name: ai-travel-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    # Limit Redis memory usage
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB with resource limits
  mongodb:
    image: mongo:7
    container_name: ai-travel-mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_pass
      MONGO_INITDB_DATABASE: ai_travel_analytics
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./backend/sql/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    # Resource limits for development
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
  redis_dev_data:
  mongodb_dev_data:
